# This is a config for E2B sandbox template.
# You can use template ID (wyagyrx4gb0e7qs8l5ck) or template name (lovalble-clone-panicz-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("lovalble-clone-panicz-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovalble-clone-panicz-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovalble-clone-panicz-test')

team_id = "16b01ba2-521a-4240-a47b-b7b7bb8dba48"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lovalble-clone-panicz-test"
template_id = "wyagyrx4gb0e7qs8l5ck"
